name: Refresh Yuusei.txt Link and Checksum

on:
  push:
    paths:
      - 'Yuusei.txt'
  schedule:
    - cron: '0 0 * * 0' # Chạy lúc 00:00 UTC mỗi Chủ Nhật

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate Checksums and Generate Link
        id: calculate
        run: |
          FILE_SHA=$(sha256sum Yuusei.txt | awk '{print $1}')
          MD5_CHECKSUM=$(md5sum Yuusei.txt | awk '{print $1}')
          RAW_LINK="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Yuusei.txt?v=$FILE_SHA"
          echo "raw_link=$RAW_LINK" >> $GITHUB_OUTPUT
          echo "md5=$MD5_CHECKSUM" >> $GITHUB_OUTPUT

      - name: Update README
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: |
          sed -i -E \
            -e "s~(Link download:).*~\1 ${{ steps.calculate.outputs.raw_link }}~" \
            -e "s~(Checksum:).*~\1 ${{ steps.calculate.outputs.md5 }}~" \
            README.md

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update Yuusei.txt link and checksum"
          git push
