name: Refresh Raw Link and Checksum

on:
  push:
    paths:
      - 'Yuusei.txt'

jobs:
  refresh-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get file's SHA and construct raw link
        id: get-link
        run: |
          FILE_SHA=$(sha256sum Yuusei.txt | awk '{print $1}')
          RAW_LINK="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/Yuusei.txt?v=$FILE_SHA"
          echo "::set-output name=raw_link::$RAW_LINK"

      - name: Calculate MD5 checksum
        id: get-checksum
        run: |
          MD5_CHECKSUM=$(md5sum Yuusei.txt | awk '{print $1}')
          echo "::set-output name=md5::$MD5_CHECKSUM"

      - name: Update README with new link and checksum
        if: github.ref == 'refs/heads/main'
        run: |
          # Tạo nội dung mới cho README.md
          NEW_README=$(cat <<EOF
          # Adblock
          Link download: ${{ steps.get-link.outputs.raw_link }}
          ! Checksum: ${{ steps.get-checksum.outputs.md5 }}

          # Phần còn lại của README.md
          $(cat README.md | tail -n +3) # Lấy nội dung từ dòng thứ 3 trở đi
          EOF
          )
          echo "$NEW_README" > README.md # Ghi nội dung mới vào README.md

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with refreshed raw link and checksum"
          git push origin main
